#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config ~/.config/picom/picom.conf &
pgrep -x feh > /dev/null || feh --bg-fill ~/.config/bspwm/debbg.jpg &
~/.config/polybar/launch.sh &
pgrep -x dunst > /dev/null || dunst &
pgrep -x lxpolkit > /dev/null || lxpolkit &
pgrep -x redshift > /dev/null || redshift &
pgrep -x openrgb > /dev/null || openrgb --profile "a" &
xrandr -r 165

bspc monitor -d  󱃢   
# I II III IV V

bspc config border_width         3
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox-esr desktop='^1' follow=on
bspc rule -a Thunar desktop='^2' follow=on
bspc rule -a kitty desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config active_border_color \#8fbcbb
bspc config normal_border_color \#000000
bspc config focused_border_color \#8fbcbb


